version: '3'
services:

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   networks:
  #     - rabbitmq_go_net
  #   restart: unless-stopped

  # db_postgres:
  #   image: postgres:latest
  #   container_name: db_postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: ghostmedb
  #   networks:
  #     - rabbitmq_go_net
  #   restart: unless-stopped

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   volumes:
  #     - './nginx.conf:/etc/nginx/nginx.conf:ro'
  #   depends_on:
  #     - api
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - rabbitmq_go_net
  #   restart: always

  # api:
  #   build:
  #     context: api
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - rabbitmq_go_net
  #   restart: unless-stopped
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - db_conn_string = postgresql+asyncpg://jagac:123@db_postgres/ghostmedb
  #     - mq_conn_string = amqp://guest:guest@rabbitmq:5672/

  # llmservice:
  #   build:
  #     context: llmservice
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - rabbitmq_go_net
  #   environment:
  #     - db_conn_string = postgresql+asyncpg://jagac:123@db_postgres/ghostmedb
  #     - mq_conn_string = amqp://guest:guest@rabbitmq:5672/

  emailservice:
    build:
      context: emailservice
    networks:
      - rabbitmq_go_net
    restart: unless-stopped
    environment:
      - gmail pass

  # etlservice:
  #   build:
  #     context: etlservice
  #   networks:
  #     - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
