services:

  rabbitmq:
    image: rabbitmq:3.13.1-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_go_net
    restart: unless-stopped

  db_postgres:
    image: postgres:alpine
    container_name: db_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ghostmedb
    networks:
      - rabbitmq_go_net
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
    depends_on:
      - api
    ports:
      - "8080:80"
    networks:
      - rabbitmq_go_net
    restart: always

  api:
    build:
      context: api
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net
    restart: unless-stopped
    environment:
      - DB_CONN_STRING=${ASYNC_DB_CONN_STRING}
      - MQ_CONN_STRING=${MQ_CONN_STRING}

  llmservice:
    build:
      context: llmservice
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net
    environment:
      DB_CONN_STRING: ${SYNC_DB_CONN_STRING}
      MQ_CONN_STRING: ${MQ_CONN_STRING}
      EMBEDDING_MODEL: sentence-transformers/all-MiniLM-L6-v2
      LLM: llama-2-7b-chat.ggmlv3.q2_K.bin
    volumes:
      - ./llmservice/model:/app/model

  emailservice:
    build:
      context: emailservice
    ports:
      - 8000:8000
    networks:
      - rabbitmq_go_net
    restart: unless-stopped
    environment:
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}

  etlservice:
    build:
      context: etlservice
    networks:
      - rabbitmq_go_net
    environment:
      DB_CONN_STRING: ${ETL_DB_CONN_STRING}

networks:
  rabbitmq_go_net:
    driver: bridge
