version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_go_net
    restart: always

  db_postgres:
    image: postgres:alpine
    container_name: db_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jagac
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ghostmedb
    networks:
      - rabbitmq_go_net
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
    depends_on:
      - api
    ports:
      - "8080:80"
    networks:
      - rabbitmq_go_net
    restart: always

  api:
    build:
      context: api
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net
    restart: always

  llmservice:
    build:
      context: llmservice
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net
    restart: always

  emailservice:
    build:
      context: emailservice
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net
    restart: always

  etlservice:
    build:
      context: etlservice
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net
    restart: always

networks:
  rabbitmq_go_net:
    driver: bridge
