version: '3'
services:
  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmq'
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      ports:
        - '5672:5672'
        - '15672:15672'
      networks:
        - rabbitmq_go_net
  app:
    build:
      context: pdfproducer
    depends_on:
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
       
    networks:
      - rabbitmq_go_net

  nginx:
    image: nginx:latest
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
    depends_on:
      - app
    ports:
      - "8080:80"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 10
    networks:
      - rabbitmq_go_net
      
  scrapers:
    build:
      context: courseetl
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net

  db_postgres:
    image: postgres:alpine
    container_name: db_postgres
    ports:
        - "5432:5432"

    environment:
        POSTGRES_USER: jagac
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: ghostmedb

    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

    networks:
      - rabbitmq_go_net


networks:
  rabbitmq_go_net:
    driver: bridge
